name: build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    strategy:
      matrix:
        version: [8, 11, 17]
        include:
          - version: 11
            bazel: yes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          cache: maven
      - name: Maven install, test skipped
        run: mvn install -DskipTests
      - name: Maven test
        run: mvn test
      - name: Run Gradle example
        run: ./gradlew build run --no-daemon
        working-directory: examples/gradle
      - name: Run Gradle ICU example
        run: ./gradlew build run --no-daemon
        working-directory: examples/gradle-icu
      - if: ${{ matrix.bazel }}
        name: Run Bazel example
        run: bazel build //:l10nbazel; bazel-bin/l10nbazel
        working-directory: examples/bazel-local
      - if: ${{ matrix.bazel }}
        name: Run Bazel ICU example
        run: bazel build //:l10nbazel; bazel-bin/l10nbazel
        working-directory: examples/bazel-icu-local



